### ISSUE TITLE
Give roles as rewards

### ISSUE THREAD

**Issue by louanfontenele** [e-enes/Invitron#11]
Give roles when reaching a invited target.

Example:
- If the user invited 50 people, the user receives a X role.
- If the user invited 100 people, the user receives a Y role.

**Comment by e-enes** [comment]
Will be added in the next update, thanks for your suggestion!

**Comment by louanfontenele** [comment]
> Will be added in the next update, thanks for your suggestion!

When will you update?

**Comment by e-enes** [comment]
> When will you update?

I plan to finish it in about ~2 weeks, you can follow the progress [here](https://github.com/e-enes/discord-invite-tracker/tree/v2)

**Comment by e-enes** [comment]
Hi, the update is available [(v2).](https://github.com/e-enes/Invitron/tree/v2). It will be merged as soon as the README.md is available but you can clone the repository, complete the `.env` and `src/config.ts` then `pnpm build && pnpm start`. 

Please note that we went from `npm` to `pnpm`. To install `pnpm`, do `npm i -g pnpm`.

Don't hesitate to open a issue again if you come across a bug, or reach out to me on discord (`e.enes`) if you require assistance in getting the bot up and running!
